### ISSUE TITLE
Missing functionality described in documentations

### ISSUE THREAD

**Issue by jan-joska** [peterdol/azure-functions-route-priority#1]
Documentation shows samples using IFunctionsHostBuilder

```
public override void Configure(IFunctionsHostBuilder builder)
{
   // add this to the Configure method in your Startup.cs
   builder.AddRoutePriority();
}
```

The code however does not contain extensions made to `IFunctionHostBuilder` only older `IWebJobsBuilder` in file `WebJobsBuilderExtensions`

This may indicate a forgotten commit?

**Comment by peterdol** [comment]
Yes, I did not yet have time to implement this yet. In the meantime you can use it like this (untested, but I think it should work)

public override void Configure(IFunctionsHostBuilder builder)
        {
            // IWebJobsBuilders instance
            var webBuilder = builder.Services.AddWebJobs(x => { return; });
            webBuilder.AddRoutePriority();
        }

**Comment by jan-joska** [comment]
> Yes, I did not yet have time to implement this yet. In the meantime you can use it like this (untested, but I think it should work)
> 
> public override void Configure(IFunctionsHostBuilder builder)
> {
> // IWebJobsBuilders instance
> var webBuilder = builder.Services.AddWebJobs(x => { return; });
> webBuilder.AddRoutePriority();
> }

Wow, thank your for your reply. I will test it.

**Comment by jan-joska** [comment]
The proposed solution works perfectly. Thank you.
